### ISSUE TITLE
Structure of peripheral object seems to differ between iOS and Android

### ISSUE THREAD

**Issue by lhitc** [EddyVerbruggen/nativescript-bluetooth#1]
On iOS, from what I see in the code, a "peripheral" object appears to have the structure

    {
        UUID: ...,
        name: ...,
        RSSI: ...,
        state: ...
    }

while on Android I see

    {
        type: ...,
        RSSI: ...,
        device: {
            name: ...,
            address: ...
        },
        advertisement: ...
    }

where UUID and address appear to be used synonymous in regard to consecutive actions like service discovery.

I would expect the structure to be identical regardless of OS.

**Comment by EddyVerbruggen** [comment]
Yes me too - I think on Android < 5 it is though, I'll make sure it's streamlined!

**Comment by EddyVerbruggen** [comment]
That's settled now; the iOS, Android <5 and Android >=5 structures now all have RSSI, UDID and name. The other bits are subject to change.
