### ISSUE TITLE
value of WriteOptions missing

### ISSUE THREAD

**Issue by t4deon** [EddyVerbruggen/nativescript-bluetooth#10]
in bluetooth.d.ts is the value missing in interface WriteOptions. 
Currently, it is: 
      export interface WriteOptions extends CRUDOptions {}

But it needs to be:
    export interface WriteOptions extends CRUDOptions {
      value: any;
    }

I would push the change to a new branch but I'm not authorized to do so.
It would be great if you could apply the change. Thanks in advance.

**Comment by EddyVerbruggen** [comment]
Great find! That's what Pull Requests are for btw. Are you willing to create one? :)

**Comment by t4deon** [comment]
I tried to create a new branch but I don't have permission for that. So creating a pull request will not work as both branches would be 'master', right? But if I could, I would :)

**Comment by tkaarrela** [comment]
Has this fix been released to npm? I still need to manually do this fix in my project after tns install...

**Comment by EddyVerbruggen** [comment]
@tkaarrela Ah, nope.. but it has now (1.1.3)!
