### ISSUE TITLE
Unable to detect mobile phones and laptops

### ISSUE THREAD

**Issue by Suralal001** [EddyVerbruggen/nativescript-bluetooth#123]
The demo-ng app is not able to detect mobile devices and laptops. but I could find that it was able to discover smartwatch Bluetooth.

**Comment by farfromrefug** [comment]
@Suralal001 I think it s normal. An't those bluetooth 2.0 devices? That module is for BLE devices only

**Comment by suralal** [comment]
Is there any possible way to connect with a raspberry pi.i am not sure with the Bluetooth version of it

**Comment by farfromrefug** [comment]
Yes you can easily create a BLE device on Pi. Look at bleno (there s an example [here](https://github.com/EddyVerbruggen/nativescript-bluetooth/tree/v2/ble_server_test))

**Comment by suralal** [comment]
I wanted to transfer data from mobile app to pi using the plugin.hope that would work

**Comment by farfromrefug** [comment]
Yes you can. I am closing that issue as it is getting out of topic. Please use Slack for those kind of questions
