### ISSUE TITLE
Problems writing after NS 6 + NS-BLE Beta update

### ISSUE THREAD

**Issue by AsgerCode** [EddyVerbruggen/nativescript-bluetooth#150]
Hello, I would like some help regarding the write() function.

It worked awesomely right before updating to NS6 and the nativescript-bluetooth@beta but now I am getting this error:

`JS: write error: {
JS:   "msg": "error_function_call",
JS:   "method": "write",
JS:   "status": 138,
JS:   "args": {
JS:     "peripheralUUID": "D0:CF:5E:1B:B0:76",
JS:     "serviceUUID": "d8b5a80c-17c5-11e8-b642-0ed5f89f718b",
JS:     "characteristicUUID": "d8b5aa1e-17c5-11e8-b642-0ed5f89f718b",
JS:     "value": "0x05"
JS:   }
JS: }`

I double checked everything and seems like the call is broken on the framework or something. What does the status 138 mean?

Best

**Comment by farfromrefug** [comment]
@AsgerCode Using the beta sending "0x05" wont work anymore. Just send 0x05 
Now for your error. I suppore you are on andoird ? (please always mention all versions you are using...) It seems 138 is GATT_MORE which is an undocumented error...
Maybe sending the value in the right format will be enough.

**Comment by AsgerCode** [comment]
@farfromrefug Thanks for clearing that up. A few calls are now working as intended. Yes I am developing for Android.
