### ISSUE TITLE
ManufacturerData in release 2.0.0-beta.23

### ISSUE THREAD

**Issue by j99ht** [EddyVerbruggen/nativescript-bluetooth#154]
I have migrated my app to Nativescript 6 and nativescript-bluetooth 2.0.0-beta.23

I have two issues with thie release:
- Now I receive the same device multiple times in the same scan period, while it was received only one in 1.3.1 Is there any way to configure this?
- I cannot access to manufacturerDataBytes anymore. I see ManufacturerID, but I do not see the rest of the information. How could I get this?

**Comment by farfromrefug** [comment]
@j99ht multiple events are intended. It is especially needed when advertisment data change.
```manufacturerDataBytes``` is now ```manufacturerData```. It is part of the advertisment data. Now it is an ```ArrayBuffer```

**Comment by j99ht** [comment]
Thanks. I works now
