### ISSUE TITLE
[v2.0] serviceUUIDs getter crashes with "Cannot read property 'size' of null"

### ISSUE THREAD

**Issue by baybal** [EddyVerbruggen/nativescript-bluetooth#168]
I'm trying to read seriveUUIDs getter on scan result, and I get the following:

Exception has occurred: TypeError
TypeError: Cannot read property 'size' of null
    at ScanAdvertisment.get [as serviceUUIDs]
    at Object.onDiscovered [as onPeripheralDiscovered]
    at Object.ScanCallBackImpl.onScanResult

It looks like this.scanRecord.getServiceUuids() returns null

**Comment by farfromrefug** [comment]
@baybal fixed in 3.0.0-beta.9 (beta)

**Comment by baybal** [comment]
@farfromrefug where is that 3.0 beta?

**Comment by farfromrefug** [comment]
Npm beta
