### ISSUE TITLE
Possible Android issues with tns_modules

### ISSUE THREAD

**Issue by NirLevanon** [EddyVerbruggen/nativescript-bluetooth#17]

**Comment by EddyVerbruggen** [comment]
??

**Comment by NirLevanon** [comment]
My apologies, I wasn't able to copy the errors I had in Genymotion. In any case, it had nothing to do with NS-BL, so I'll close it now. :smile:

**Comment by EddyVerbruggen** [comment]
Lol, thanks for clearing that up 😉
