### ISSUE TITLE
How to send json data

### ISSUE THREAD

**Issue by leocrawf** [EddyVerbruggen/nativescript-bluetooth#184]
I want to send a complex json object. How would I do that?

**Comment by leocrawf** [comment]
I am hoping this will work: 
https://stackoverflow.com/questions/35971566/store-a-json-object-in-arraybuffer

**Comment by manojdcoder** [comment]
Can you please be more specific, where you want to send complex json object?

**Comment by leocrawf** [comment]
I would love to send data from one android phone to another android phone or from android to ios phone all running the same app.

**Comment by farfromrefug** [comment]
You have to handle it yourself. Nor the Ble protocol nor this plugin directly support sending json objects.
