### ISSUE TITLE
Wait until location permission is granted

### ISSUE THREAD

**Issue by NirLevanon** [EddyVerbruggen/nativescript-bluetooth#19]
I need a way to poll when I call `bluetooth.requestCoarseLocationPermission()` to know when the user has allowed or rejected the request.

**Comment by NirLevanon** [comment]
I recommend looking at https://github.com/NathanaelA/nativescript-permissions

**Comment by EddyVerbruggen** [comment]
There's [this](https://github.com/EddyVerbruggen/nativescript-bluetooth/blob/master/bluetooth.d.ts#L167)
