### ISSUE TITLE
Difference between IOS and Android on connected

### ISSUE THREAD

**Issue by dkallkro** [EddyVerbruggen/nativescript-bluetooth#23]
Hi,

I get diffent result when Perihicals are connected:
It works perfectly in IOS ("UUID":"E2E4278A-056A-4B22-947D-37010C1FE970"),
but on android ("UUID":"00:1E:C0:2F:EC:03") i get different UUID's. It does not seems logic???

IOS:
Peripheral connected: {"UUID":"E2E4278A-056A-4B22-947D-37010C1FE970","name":"Omega","state":"connected","services":[{"UUID":"12345678-9012-3456-7890-1234567890EE","name":{},"characteristics":[{"UUID":"12345678-9012-3456-7890-123456789000","name":{},"value":null,"properties":{"broadcast":false,"read":true,"broadcast2":false,"read2":true,"write":false,"writeWithoutResponse":true,"notify":true,"indicate":false,"authenticatedSignedWrites":false,"extendedProperties":false,"notifyEncryptionRequired":false,"indicateEncryptionRequired":false},"isNotifying":false},{"UUID":"12345678-9012-3456-7890-123456789001","name":{},"value":"SQE=","properties":{"broadcast":false,"read":false,"broadcast2":false,"read2":false,"write":false,"writeWithoutResponse":false,"notify":true,"indicate":false,"authenticatedSignedWrites":false,"extendedProperties":false,"notifyEncryptionRequired":false,"indicateEncryptionRequired":false},"isNotifying":false},{"UUID":"12345678-9012-3456-7890-123456789002","name":{},"value":"gQA4AaA5AAAA","properties":{"broadcast":false,"read":false,"broadcast2":false,"read2":false,"write":false,"writeWithoutResponse":false,"notify":true,"indicate":false,"authenticatedSignedWrites":false,"extendedProperties":false,"notifyEncryptionRequired":false,"indicateEncryptionRequired":false},"isNotifying":false},{"UUID":"12345678-9012-3456-7890-123456789003","name":{},"value":"hwGg","properties":{"broadcast":false,"read":false,"broadcast2":false,"read2":false,"write":false,"writeWithoutResponse":false,"notify":true,"indicate":false,"authenticatedSignedWrites":false,"extendedProperties":false,"notifyEncryptionRequired":false,"indicateEncryptionRequired":false},"isNotifying":false},{"UUID":"12345678-9012-3456-7890-123456789004","name":{},"value":null,"properties":{"broadcast":false,"read":false,"broadcast2":false,"read2":false,"write":false,"writeWithoutResponse":false,"notify":true,"indicate":false,"authenticatedSignedWrites":false,"extendedProperties":false,"notifyEncryptionRequired":false,"indicateEncryptionRequired":false},"isNotifying":false}]}]}

Android:
Peripheral connected: {"UUID":"00:1E:C0:2F:EC:03","name":"Omega","state":"connected","services":[{"UUID":"1800","characteristics":[{"UUID":"2a00","name":"2a00","properties":{"read":true,"write":true,"writeWithoutResponse":false,"notify":false,"indicate":false,"broadcast":false,"authenticatedSignedWrites":false,"extendedProperties":false},"descriptors":[]},{"UUID":"2a01","name":"2a01","properties":{"read":true,"write":false,"writeWithoutResponse":false,"notify":false,"indicate":false,"broadcast":false,"authenticatedSignedWrites":false,"extendedProperties":false},"descriptors":[]},{"UUID":"2a04","name":"2a04","properties":{"read":true,"write":false,"writeWithoutResponse":false,"notify":false,"indicate":false,"broadcast":false,"authenticatedSignedWrites":false,"extendedProperties":false},"descriptors":[]}]},{"UUID":"1801","characteristics":[]},{"UUID":"12345678-9012-3456-7890-1234567890ee","characteristics":[{"UUID":"12345678-9012-3456-7890-123456789000","name":"12345678-9012-3456-7890-123456789000","properties":{"read":true,"write":false,"writeWithoutResponse":true,"notify":true,"indicate":false,"broadcast":false,"authenticatedSignedWrites":false,"extendedProperties":false},"descriptors":[{"UUID":"2902","value":null}]},{"UUID":"12345678-9012-3456-7890-123456789001","name":"12345678-9012-3456-7890-123456789001","properties":{"read":false,"write":false,"writeWithoutResponse":false,"notify":true,"indicate":false,"broadcast":false,"authenticatedSignedWrites":false,"extendedProperties":false},"descriptors":[{"UUID":"2902","value":null}]},{"UUID":"12345678-9012-3456-7890-123456789002","name":"12345678-9012-3456-7890-123456789002","properties":{"read":false,"write":false,"writeWithoutResponse":false,"notify":true,"indicate":false,"broadcast":false,"authenticatedSignedWrites":false,"extendedProperties":false},"descriptors":[{"UUID":"2902","value":null}]},{"UUID":"12345678-9012-3456-7890-123456789003","name":"12345678-9012-3456-7890-123456789003","properties":{"read":false,"write":false,"writeWithoutResponse":false,"notify":true,"indicate":false,"broadcast":false,"authenticatedSignedWrites":false,"extendedProperties":false},"descriptors":[{"UUID":"2902","value":null}]},{"UUID":"12345678-9012-3456-7890-123456789004","name":"12345678-9012-3456-7890-123456789004","properties":{"read":false,"write":false,"writeWithoutResponse":false,"notify":true,"indicate":false,"broadcast":false,"authenticatedSignedWrites":false,"extendedProperties":false},"descriptors":[{"UUID":"2902","value":null}]}]}]}

**Comment by EddyVerbruggen** [comment]
That's by design (not the plugin's design, the OS design), also see this issue which has a very similar implementation: https://github.com/don/cordova-plugin-ble-central/issues/279
