### ISSUE TITLE
Provide a way to toggle console logging.

### ISSUE THREAD

**Issue by Christopotamus** [EddyVerbruggen/nativescript-bluetooth#34]
Hello,

I have an app that produces a ton of bluetooth traffic (it's transferring a devices firmware over bluetooth) and on ios, the console actually completely freezes and detaches due to excessive console logging. I've tested disabling console logging in bluetooth.android.js and bluetooth.ios.js and have seen the issue disappear.

I can see how console logging could be useful, but we should provide a way to either enable or disable it. 

Would you be accepting to a pull request with some way to toggle debug output on or off?

**Comment by davorpeic** [comment]
Have you tried this? https://github.com/EddyVerbruggen/nativescript-bluetooth#setcharacteristiclogging

**Comment by richardlford** [comment]
I've noticed in the latest version that there are some console logs that are not protected by characteristicLogging. For example, in the Bluetooth._findCharacteristic function for ios.

**Comment by bradmartin** [comment]
This will be fixed with the 2.0.0 release - small breaking changes, hence the major bump but `debug` prop will enable/disable logs.
