### ISSUE TITLE
Device not detected

### ISSUE THREAD

**Issue by dpkchwdhry1** [EddyVerbruggen/nativescript-bluetooth#38]
When I try to run the demo app in my phone "Redmi Note 3" Android version "6.0.1", I am not able to detect any other device, provided both the location and bluetooth are enabled in all the devices. Kindly help.

**Comment by EddyVerbruggen** [comment]
Are the devices you're trying to connect to BLE peripherals? Which?

**Comment by dpkchwdhry1** [comment]
No, I am only trying to connect to another "Redmi note 3".

**Comment by EddyVerbruggen** [comment]
I don't think that's supposed to work. Try a BLE peripheral please and reopen if needed.

**Comment by johnjacobkenny** [comment]
@EddyVerbruggen are there any similar libraries that you know of which supports non BLE peripherals? Thanks.
