### ISSUE TITLE
Should NSData be an ArrayBuffer?

### ISSUE THREAD

**Issue by vtjon** [EddyVerbruggen/nativescript-bluetooth#4]
I am starting to do more work with my BLE-to-serial adapter. When I catch the notify event, I am expecting binary data. My return type appears to be NSData. Should this be marshaled to an ArrayBuffer? I'm not sure what is the best way to handle binary data on the iOS side.

**Comment by EddyVerbruggen** [comment]
It would be best to have Android and iOS return the same type so yeah that would be best.

In what way would you marshal it to work best for your usecase?

**Comment by vtjon** [comment]
In my case, I believe I'm going to ultimately need it as a byte array.

**Comment by EddyVerbruggen** [comment]
Would it help if you got [this data object](https://github.com/EddyVerbruggen/nativescript-bluetooth/blob/master/bluetooth.ios.js#L133) back instead?

**Comment by vtjon** [comment]
Yes, I believe that will work. I am pushing the value into a buffer using the [node buffer module](https://www.npmjs.com/package/buffer) and it looks like it will work. I am converting another module that uses the node serialport package so I'm not totally sure on some of the inner workings yet.

**Comment by EddyVerbruggen** [comment]
Please check the 1.1.0 version I released today (updated sample in the readme and demo app).

**Comment by vtjon** [comment]
@EddyVerbruggen Just to follow up, this new release seems to be working for my situation! Thanks for the quick work.
