### ISSUE TITLE
Enable Bluetooth directly from app. 

### ISSUE THREAD

**Issue by aaayushsingh** [EddyVerbruggen/nativescript-bluetooth#43]
Right now, this only supports checking if Bluetooth is enabled or not. It'd be great if it allowed turning on Bluetooth from within the application. This way, the user wouldn't have to do it manually.

**Comment by EddyVerbruggen** [comment]
AFAIK that's not allowed.

**Comment by aaayushsingh** [comment]
@EddyVerbruggen In android, apps can enable bluetooth. It shows up a prompt that user can choose allow or deny from. I think that's better then opening up notifications and then enabling Bluetooth.

**Comment by EddyVerbruggen** [comment]
Ah interesting. Can you share an app that does that, or even better, point me at the relevant docs/code?

**Comment by aaayushsingh** [comment]
@EddyVerbruggen 
`BluetoothAdapter mBluetoothAdapter = BluetoothAdapter.getDefaultAdapter(); 
    mBluetoothAdapter.enable(); `

we'll need these permissions in manifest for native android applications
`<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>`

solution from [this](https://stackoverflow.com/a/6276516/6753515) page.

here's a screenshot. 
![image](https://user-images.githubusercontent.com/19550852/28519039-bcb9aaf8-7087-11e7-93e3-494a35c2b501.png)

Also, can you guide me on how to implement this? I'd like to do this one on my own, and then a PR maybe.

**Comment by EddyVerbruggen** [comment]
PR #44 that adds this feature has just been merged. You can expect a new version on npm soon.

**Comment by aaayushsingh** [comment]
@EddyVerbruggen mind if I implement this in the Bluetooth demo app?

**Comment by EddyVerbruggen** [comment]
@aaayushsingh Ha, thanks for offering but I'm working on a better implementation of this feature and also have an updated version of the demo app locally. Expecting to push it in a few hours!

**Comment by EddyVerbruggen** [comment]
@aaayushsingh The demo has been updated and 1.2.0 has been published.

**Comment by aaayushsingh** [comment]
So now I can boast in front of my friends about my first real PR getting merged. 

Thanks.

**Comment by EddyVerbruggen** [comment]
Yes sir you can! Thanks so much, and I hope this is the first of many to any repo out there 👍 👍
