### ISSUE TITLE
Update interface while searching device

### ISSUE THREAD

**Issue by yenchieh** [EddyVerbruggen/nativescript-bluetooth#49]
Hello,
I couldn't figure out how to update view while searching device.
Here is my code
searching device function:

app.component.ts
```
log: string = "Start test";
startScanning() {
        ble.startScanning({
            serviceUUIDs: [],
            seconds: 5,
            onDiscovered: (peripheral) => {
                if (peripheral.name == "SWING") {
                    this.stopScanning();
                    this.updateLog(`Device Name: ${peripheral.name}`); //Update view
                }
        }).then(() => {
            this.updateLog("scanning completed");
        }, (err) => {
            console.error(`Error on scanning: ${err}`);
        })
    }
```

app.component.html
```
 <TextView text="{{ log }}" editable="false"></TextView>
```

While it scanning, it won't update the log to the view before 5 seconds which finishes the `ble.startScanning`.
I believe that I do not fully understand RxJs (Promise) functionality, so I couldn't figure out this issue.

Thank you.

**Comment by EddyVerbruggen** [comment]
dupe @ https://stackoverflow.com/questions/45829725/nativescript-ble-update-interface-while-searching-device-by-using-nativescript
