### ISSUE TITLE
bluetooth not detect devices

### ISSUE THREAD

**Issue by peppeg85** [EddyVerbruggen/nativescript-bluetooth#60]
hi, i've read the other topic about bluetooth detecting problems, but i still can't resolve it, i'm new in nativescript and mobile programming, this is my discovering function, it works until the enable  function, then the 
`onDiscovered: function (peripheral) {
                                console.log("Periperhal found with UUID: " + peripheral.UUID);
                            }`

don't return nothing,
where am i wrong?
`exports.bt = function () {
    bluetooth.isBluetoothEnabled().then(
        function (enabled) {
            console.log("Enabled? " + enabled);
            if (!enabled) {
                bluetooth.enable().then(
                    function(enabled) {
                        console.log("attivato "+ enabled);
                        bluetooth.startScanning({
                            serviceUUIDs: [],
                            seconds: 10,
                            onDiscovered: function (peripheral) {
                                console.log("Periperhal found with UUID: " + peripheral.UUID);
                            }
                        }).then(function () {
                            console.log("scanning complete ");
                            console.log("Periperhal found with UUID: " + peripheral.UUID);
                        }, function (err) {
                            console.log("error while scanning: " + err);
                        });
                    }
                );
            }
        }
    );
};`
thank you for your help

**Comment by peppeg85** [comment]
sorry, now i've seen that this library is for BLE, my devices are BT standard, could this be the problem?

**Comment by giordanocardillo** [comment]
+1 is this library only for BLE? and Why?

**Comment by EddyVerbruggen** [comment]
Correct. This plugin is for BLE devices.

**Comment by giordanocardillo** [comment]
Is there any way I can modify this to work with Bluetooth standard devices?
