### ISSUE TITLE
Android can't connect to BLE 4.0

### ISSUE THREAD

**Issue by francorobles** [EddyVerbruggen/nativescript-bluetooth#84]
iOS has no trouble connecting to BLE 4.0 only on Android.

**Comment by EddyVerbruggen** [comment]
Is there a device this can be tested with?

**Comment by francorobles** [comment]
Hi @EddyVerbruggen, thanks for responding. Its 802.11 b/g/n, Bluetooth V4.0 + EDR.

**Comment by EddyVerbruggen** [comment]
I have an S8 so the device to test the plugin on is pretty similar, but I'd also require the peripheral to test with.. is it something I can buy anywhere perhaps?

**Comment by francorobles** [comment]
It is connecting to a Raspberry Pi 3B. Here is the specs https://hackaday.com/2016/02/28/introducing-the-raspberry-pi-3/

**Comment by francorobles** [comment]
Hell @EddyVerbruggen . We fixed this issue by doing the following:

- Targeted 2.5.1 tns core modules.
- Added app.gradle targeting google play services 9.8.0
