### ISSUE TITLE
detecting when user disables bluettooth on the device (android)

### ISSUE THREAD

**Issue by bluelemonade** [EddyVerbruggen/nativescript-bluetooth#92]
first of all, great plugin, I am using it in an vuejs project. 

one thing, when the client is lost or disabled  the onDisconnected is fired, but how can I detect when bluetooth is disabled on the device?

regards

**Comment by EddyVerbruggen** [comment]
Well, there is no event you can listen to, but there is https://github.com/EddyVerbruggen/nativescript-bluetooth#isbluetoothenabled

**Comment by bluelemonade** [comment]
fine, I can use it and check in intervals...
or is there a timeout option for onNotify
